name: Build and Deploy PostOffice Service

on:
  push:
    branches:
      - Turkcell-Bulut

jobs:

  # Build PostOffice
  Build:

    # Set Environment Variables
    env:
      SERVER_NAME: ${{secrets.SERVER_NAME}}
      PROJECT_ROOT: ${{secrets.PROJECT_ROOT}}
      SUDO_PASSWORD: ${{secrets.SUDO_PASSWORD}}

      # Set Log Files
      LOG_FILE: ${{secrets.LOG_FILE}}
      LOG_DIR: ${{secrets.LOG_DIR}}
      LOG_SERVICE_ERROR: ${{secrets.LOG_SERVICE_ERROR}}
      LOG_SERVICE_ACCESS: ${{secrets.LOG_SERVICE_ACCESS}}

      # Set Database Variables
      DB_HOSTNAME: ${{secrets.DB_HOSTNAME}}
      DB_PORT: ${{secrets.DB_PORT}}
      DB_PASSWORD: ${{secrets.DB_PASSWORD}}
      DB_NAME: ${{secrets.DB_NAME}}
      DB_USERNAME: ${{secrets.DB_USERNAME}}

      KAFKA_HOSTNAME: ${{secrets.KAFKA_HOSTNAME}}
      KAFKA_PORT: ${{secrets.KAFKA_PORT}}

      FILE_MANUFACTURER: ${{secrets.FILE_MANUFACTURER}}
      FILE_MODEL: ${{secrets.FILE_MODEL}}
      FILE_GSM_OPERATOR: ${{secrets.FILE_GSM_OPERATOR}}
      FILE_SIM: ${{secrets.FILE_SIM}}
      FILE_MODEM: ${{secrets.FILE_MODEM}}
      FILE_DATA_SEGMENT: ${{secrets.FILE_DATA_SEGMENT}}
      FILE_MEASUREMENT_TYPE: ${{secrets.FILE_MEASUREMENT_TYPE}}
      FILE_VERSION: ${{secrets.FILE_VERSION}}
      FILE_STATUS: ${{secrets.FILE_STATUS}}
      FILE_DEVICE: ${{secrets.FILE_DEVICE}}
      FILE_CALIBRATION: ${{secrets.FILE_CALIBRATION}}
      FILE_PROJECT: ${{secrets.FILE_PROJECT}}
      FILE_CONNECTION: ${{secrets.FILE_CONNECTION}}
      FILE_COMMAND: ${{secrets.FILE_COMMAND}}

    # Set Postgres Service
    services:
      db:
        image: postgres:16
        env:
          POSTGRES_USER: ${{secrets.DB_USERNAME}}
          POSTGRES_PASSWORD: ${{secrets.DB_PASSWORD}}
          POSTGRES_DB: ${{secrets.DB_NAME}}
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    # Set PostOffice Service
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Install Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'
      - name: Set TERM
        run: echo "TERM=xterm-256color" >> $GITHUB_ENV
      - name: Update pip
        run: python -m pip install --upgrade pip
      - name: Install dependencies
        run: pip install -r requirements.txt
      - name: Set PYTHONPATH
        run: echo "PYTHONPATH=$PYTHONPATH:/home/runner/work/***/***" >> $GITHUB_ENV
      - name: Run Post Test
        run: |
          pip install pytest
          pytest -s --disable-warnings -v tests/test_Data_Post.py
  
  # Deploy PostOffice
  Deploy:
    runs-on: ubuntu-latest
    needs: [Build]
    steps:
      - name: deploy to ubuntu server
        uses: appleboy/ssh-action@master
        with:
          host: ${{secrets.PROD_HOST}}
          username: ${{secrets.PROD_USERNAME}}
          password: ${{secrets.PROD_PASSWORD}}
          script: |
            cd ~
            source /home/postoffice/PostOffice/PostOffice_ENV/bin/activate
            source Update.sh
            echo "Deployed Successfully"
