name: Build and Deploy PostOffice Service

on:
  push:
    branches:
      - Turkcell-Bulut

jobs:
  job1:
    env:
      SERVER_NAME: ${{secrets.SERVER_NAME}}
      LOG_FILE: ${{secrets.LOG_FILE}}
      DB_HOSTNAME: ${{secrets.DB_HOSTNAME}}
      DB_PORT: ${{secrets.DB_PORT}}
      DB_PASSWORD: ${{secrets.DB_PASSWORD}}
      DB_NAME: ${{secrets.DB_NAME}}
      DB_USERNAME: ${{secrets.DB_USERNAME}}
      FILE_MANUFACTURER: ${{secrets.FILE_MANUFACTURER}}
      FILE_MODEL: ${{secrets.FILE_MODEL}}
      FILE_GSM_OPERATOR: ${{secrets.FILE_GSM_OPERATOR}}
      FILE_SIM: ${{secrets.FILE_SIM}}
      FILE_MODEM: ${{secrets.FILE_MODEM}}
      FILE_DATA_SEGMENT: ${{secrets.FILE_DATA_SEGMENT}}
      FILE_MEASUREMENT_TYPE: ${{secrets.FILE_MEASUREMENT_TYPE}}
      FILE_VERSION: ${{secrets.FILE_VERSION}}
      FILE_STATUS: ${{secrets.FILE_STATUS}}
      FILE_DEVICE: ${{secrets.FILE_DEVICE}}
      FILE_CALIBRATION: ${{secrets.FILE_CALIBRATION}}
      FILE_PROJECT: ${{secrets.FILE_PROJECT}}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.12'
      - name: Update pip
        run: python -m pip install --upgrade pip
      - name: Install dependencies
        run: pip install -r requirements.txt
      - name: Set PYTHONPATH
        run: echo "PYTHONPATH=$PYTHONPATH:/home/runner/work/***/***" >> $GITHUB_ENV
      - name: Run tests
        run: |
          pip install pytest
          pytest -s --disable-warnings -v Tests/Data_Post.py